

#install and load package arules

install.packages("arules")
library(arules)
#install and load arulesViz
install.packages("arulesViz", dependencies = TRUE)
library(arulesViz)
#install and load tidyverse
install.packages("tidyverse")
library(tidyverse)
#install and load readxml
install.packages("readxml")
library(readxl)
#install and load knitr
install.packages("knitr")
library(knitr)
#load ggplot2 as it comes in tidyverse
library(ggplot2)
library("imputeTS")
#install and load lubridate
install.packages("lubridate")
library(lubridate)
#install and load plyr
install.packages("plyr")
library(plyr)
library(dplyr)


#Specify the file path to read input dataset: EstuaryVsSpecies.csv
test <- read.transactions("D:\\Researchwork_2021\\Rule filtering\\EstuaryVsSpecies.csv",  sep = ",")
transactions1<- test
summary(transactions1)
nrow(transactions1)

#Generate rules
rules <- apriori(transactions1, parameter = list(support = 0.1, confidence = 0.5, minlen = 2))

#Write output files
write(rules, file = "species_rule.csv", sep = ",")
df = read.csv("species_rule.csv",header=T) 
hist(df$lift)
summary(rules)
inspect(head(sort(rules, by ="lift"),5))
inspect(sort(sort(rules, by ="support"),by ="confidence")[1:20])
plot(rules, measure=c("support", "confidence"), shading="lift", interactive=FALSE)


# Specify the name of the focal species to be studied
# Here we are generating rules for Heritieta fomes
Heritiera_fomes.rules <- sort(subset(rules, subset = rhs %in% "Heritiera fomes"), by = "confidence")
summary(Heritiera_fomes.rules)

#Removing redundancy
Heritiera_nonredundant= (Heritiera_fomes.rules[!is.redundant(Heritiera_fomes.rules)])
inspect(Heritiera_nonredundant)
write(Heritiera_nonredundant, file = "Heritiera_fomes_NonRedundant.csv", sep = ",")

#Pruning by lift value
hist(df$lift)
Heritiera_rulesLift <- sort(subset(Heritiera_nonredundant, subset = lift >   0.2 * max(df$lift)), by="lift") 
write(Heritiera_rulesLift, file = "Heritiera_fomes_Lift.csv", sep = ",")
summary(Heritiera_rulesLift)

#Pruning based on chi-squared distribution
quality(Heritiera_rulesLift) <- cbind(quality(Heritiera_rulesLift), chiSquared = interestMeasure(Heritiera_rulesLift, measure = "chiSquared", transactions = transactions))
inspect(head(Heritiera_rulesLift, by = "chiSquared"))
Heritiera_filter_chiSquared <- sort(subset(Heritiera_rulesLift, subset = chiSquared > 6), by="chiSquared")
write(Heritiera_filter_chiSquared, file = "Heritiera_fomes_chiSquared.csv", sep = ",")
summary(Heritiera_filter_chiSquared)


# Significance test using A. "bonferroni correction" and B. "Benjamini-Hochberg correction" 


# A.  "bonferroni correction" for find out the significant rules

inspect(Heritiera_filter_chiSquared[is.significant(
  Heritiera_filter_chiSquared,
  transactions1,
  method = "chisq",
  alpha = 0.01,
  adjust = "bonferroni"
)
])

#Writing the result of Bonferroni test to a output file
write(
  (Heritiera_filter_chiSquared[is.significant(
    Heritiera_filter_chiSquared,
    transactions1,
    method = "chisq",
    alpha = 0.01,
    adjust = "bonferroni"
  )
  ]), 
  file = "Heritiera_fomes_Bonferroni.csv", sep = ",")




# B. Apply the Benjamini-Hochberg correction

quality_measures <- quality(Heritiera_filter_chiSquared)
print(quality_measures)

# Extracting chi-squared values
chisq <- quality_measures$chiSquared
print(chisq)

# Finding P value from Chi_squared measure
p_values <- sapply(chisq, function(x) pchisq(x, df = 1, lower.tail = FALSE))
print(p_values)

#adj_pvals <- p.adjust(p_values, method = "fdr")
adj_pvals <- p.adjust(p_values, method = "bonferroni")
adj_pvals

# Check which tests are significant at the 0.05 level
sig_tests <- which(adj_pvals < 0.05)
print(rules[sig_tests])
inspect(Heritiera_filter_chiSquared[which(adj_pvals < 0.05)])

write(Heritiera_filter_chiSquared[which(adj_pvals < 0.05)], file = "Heritiera_fomes_Benjamini.csv", sep = ",")


# Final output file Heritiera_fomes_filtered.csv is generated by considering both Heritiera_fomes_Bonferroni.csv and Heritiera_fomes_Benjamini.csv.




